name: Test Dash App

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          python -m unittest discover

      - name: Check if app starts (optional)
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          nohup python app.py &
          sleep 5
          curl -I http://127.0.0.1:8050
